name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:

  build:
    uses: syntax-tm/SteamAchievementManager/.github/workflows/build.yml@main
  create-release:
    runs-on: windows-latest
    needs: [build]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Create Archive
      run: |
        $items = Get-ChildItem artifacts
        $items | % { Compress-Archive -Path "$($_.FullName)\*" -DestinationPath "$($_.FullName).zip" -Force }

        Get-ChildItem -Path artifacts -Filter *.zip | Format-Table
    - uses: ncipollo/release-action@v1
      with:
        artifacts: artifacts/*.zip
        bodyFile: ./CHANGELOG.md
        draft: true
        allowUpdates: true
        artifactErrorsFailBuild: true
